//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace AMOS.Models.TRANSFER_SHIPMENT_STATUS.v1_1
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "transferShipmentStatus", Namespace = "", IsNullable = false)]
    public partial class transferShipmentStatus_1_1 : ITransferShipmentStatus
    {

        private shipmentStatusContentType[] shipmentStatusField;

        private string versionField;

        public transferShipmentStatus_1_1()
        {
            this.versionField = "1.1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipmentStatus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shipmentStatusContentType[] shipmentStatus
        {
            get
            {
                return this.shipmentStatusField;
            }
            set
            {
                this.shipmentStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shipmentStatusContentType
    {

        private shipmentStatusHeaderType shipmentStatusHeaderField;

        private shipmentStatusContentTypeShipmentStatusDetails shipmentStatusDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shipmentStatusHeaderType shipmentStatusHeader
        {
            get
            {
                return this.shipmentStatusHeaderField;
            }
            set
            {
                this.shipmentStatusHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shipmentStatusContentTypeShipmentStatusDetails shipmentStatusDetails
        {
            get
            {
                return this.shipmentStatusDetailsField;
            }
            set
            {
                this.shipmentStatusDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shipmentStatusHeaderType
    {

        private identificationType identificationField;

        private string shipmentStatusField;

        private string uuidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public identificationType identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shipmentStatus
        {
            get
            {
                return this.shipmentStatusField;
            }
            set
            {
                this.shipmentStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class identificationType
    {

        private string awbNumberField;

        private string externalShipmentNumberField;

        private string barcodeField;

        private int internalShipmentNumberField;

        private bool internalShipmentNumberFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string awbNumber
        {
            get
            {
                return this.awbNumberField;
            }
            set
            {
                this.awbNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string externalShipmentNumber
        {
            get
            {
                return this.externalShipmentNumberField;
            }
            set
            {
                this.externalShipmentNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int internalShipmentNumber
        {
            get
            {
                return this.internalShipmentNumberField;
            }
            set
            {
                this.internalShipmentNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool internalShipmentNumberSpecified
        {
            get
            {
                return this.internalShipmentNumberFieldSpecified;
            }
            set
            {
                this.internalShipmentNumberFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shipmentStatusDetailType
    {

        private string detailNumberField;

        private string detailStatusField;

        private string uuidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailNumber
        {
            get
            {
                return this.detailNumberField;
            }
            set
            {
                this.detailNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detailStatus
        {
            get
            {
                return this.detailStatusField;
            }
            set
            {
                this.detailStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class shipmentStatusContentTypeShipmentStatusDetails
    {

        private shipmentStatusDetailType[] shipmentStatusDetailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipmentStatusDetail", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public shipmentStatusDetailType[] shipmentStatusDetail
        {
            get
            {
                return this.shipmentStatusDetailField;
            }
            set
            {
                this.shipmentStatusDetailField = value;
            }
        }
    }
}