//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace AMOS.Models.TRANSFER_SHIPPED_ORDER_DETAIL_DATA.v1_0
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "transferShippedOrderDetailData", Namespace = "", IsNullable = false)]
    public partial class transferShippedOrderDetailData_1_0 : ITransferShippedOrderDetailData
    {

        private transferShippedOrderDetailDataShippedData[] shippedDataField;

        private string versionField;

        public transferShippedOrderDetailData_1_0()
        {
            this.versionField = "1.0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shippedData")]
        public transferShippedOrderDetailDataShippedData[] shippedData
        {
            get
            {
                return this.shippedDataField;
            }
            set
            {
                this.shippedDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class transferShippedOrderDetailDataShippedData
    {

        private transferShippedOrderDetailDataShippedDataShipment shipmentField;

        private shippedOrderDetailDataType[] shippedOrderDetailDataField;

        /// <remarks/>
        public transferShippedOrderDetailDataShippedDataShipment shipment
        {
            get
            {
                return this.shipmentField;
            }
            set
            {
                this.shipmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shippedOrderDetailData")]
        public shippedOrderDetailDataType[] shippedOrderDetailData
        {
            get
            {
                return this.shippedOrderDetailDataField;
            }
            set
            {
                this.shippedOrderDetailDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class transferShippedOrderDetailDataShippedDataShipment
    {

        private string awbNumberField;

        private System.DateTime awbDateField;

        private bool awbDateFieldSpecified;

        private int shipmentNumberField;

        private bool shipmentNumberFieldSpecified;

        private string shipmentDetailUUIDField;

        /// <remarks/>
        public string awbNumber
        {
            get
            {
                return this.awbNumberField;
            }
            set
            {
                this.awbNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime awbDate
        {
            get
            {
                return this.awbDateField;
            }
            set
            {
                this.awbDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool awbDateSpecified
        {
            get
            {
                return this.awbDateFieldSpecified;
            }
            set
            {
                this.awbDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int shipmentNumber
        {
            get
            {
                return this.shipmentNumberField;
            }
            set
            {
                this.shipmentNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shipmentNumberSpecified
        {
            get
            {
                return this.shipmentNumberFieldSpecified;
            }
            set
            {
                this.shipmentNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string shipmentDetailUUID
        {
            get
            {
                return this.shipmentDetailUUIDField;
            }
            set
            {
                this.shipmentDetailUUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shippedOrderDetailDataType
    {

        private shippedOrderDetailDataTypeOrderReference orderReferenceField;

        private int orderPositionNumberField;

        private string stationField;

        private string unitOfMeasureField;

        private certificateInformation[] certificateInformationField;

        private shippedOrderDetailDataTypeShippedOrderDetailItemData[] shippedOrderDetailItemDataField;

        /// <remarks/>
        public shippedOrderDetailDataTypeOrderReference orderReference
        {
            get
            {
                return this.orderReferenceField;
            }
            set
            {
                this.orderReferenceField = value;
            }
        }

        /// <remarks/>
        public int orderPositionNumber
        {
            get
            {
                return this.orderPositionNumberField;
            }
            set
            {
                this.orderPositionNumberField = value;
            }
        }

        /// <remarks/>
        public string station
        {
            get
            {
                return this.stationField;
            }
            set
            {
                this.stationField = value;
            }
        }

        /// <remarks/>
        public string unitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("certificateInformation")]
        public certificateInformation[] certificateInformation
        {
            get
            {
                return this.certificateInformationField;
            }
            set
            {
                this.certificateInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shippedOrderDetailItemData")]
        public shippedOrderDetailDataTypeShippedOrderDetailItemData[] shippedOrderDetailItemData
        {
            get
            {
                return this.shippedOrderDetailItemDataField;
            }
            set
            {
                this.shippedOrderDetailItemDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class shippedOrderDetailDataTypeOrderReference
    {

        private string customerOrderNumberField;

        private string orderUUIDField;

        /// <remarks/>
        public string customerOrderNumber
        {
            get
            {
                return this.customerOrderNumberField;
            }
            set
            {
                this.customerOrderNumberField = value;
            }
        }

        /// <remarks/>
        public string orderUUID
        {
            get
            {
                return this.orderUUIDField;
            }
            set
            {
                this.orderUUIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class certificateInformation
    {

        private string certificateTypeField;

        private System.DateTime certificateDateField;

        private bool certificateDateFieldSpecified;

        private string formTrackingNumberField;

        private string certifyingCompanyField;

        /// <remarks/>
        public string certificateType
        {
            get
            {
                return this.certificateTypeField;
            }
            set
            {
                this.certificateTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime certificateDate
        {
            get
            {
                return this.certificateDateField;
            }
            set
            {
                this.certificateDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificateDateSpecified
        {
            get
            {
                return this.certificateDateFieldSpecified;
            }
            set
            {
                this.certificateDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string formTrackingNumber
        {
            get
            {
                return this.formTrackingNumberField;
            }
            set
            {
                this.formTrackingNumberField = value;
            }
        }

        /// <remarks/>
        public string certifyingCompany
        {
            get
            {
                return this.certifyingCompanyField;
            }
            set
            {
                this.certifyingCompanyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class shippedOrderDetailDataTypeShippedOrderDetailItemData
    {

        private certificateInformation[] certificateInformationField;

        private string customsNumberField;

        private double quantityField;

        private bool quantityFieldSpecified;

        private partInformation partInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("certificateInformation")]
        public certificateInformation[] certificateInformation
        {
            get
            {
                return this.certificateInformationField;
            }
            set
            {
                this.certificateInformationField = value;
            }
        }

        /// <remarks/>
        public string customsNumber
        {
            get
            {
                return this.customsNumberField;
            }
            set
            {
                this.customsNumberField = value;
            }
        }

        /// <remarks/>
        public double quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }

        /// <remarks/>
        public partInformation partInformation
        {
            get
            {
                return this.partInformationField;
            }
            set
            {
                this.partInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class partInformation
    {

        private string partNumberField;

        private string partOwnerField;

        private object itemField;

        private string partConditionField;

        private bool hasPartManufacturerApprovalField;

        private bool hasPartManufacturerApprovalFieldSpecified;

        private System.DateTime manufacturingDateField;

        private bool manufacturingDateFieldSpecified;

        private partInformationExpiryInformation expiryInformationField;

        /// <remarks/>
        public string partNumber
        {
            get
            {
                return this.partNumberField;
            }
            set
            {
                this.partNumberField = value;
            }
        }

        /// <remarks/>
        public string partOwner
        {
            get
            {
                return this.partOwnerField;
            }
            set
            {
                this.partOwnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("batchNumberInformation", typeof(partInformationBatchNumberInformation))]
        [System.Xml.Serialization.XmlElementAttribute("serialNumber", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string partCondition
        {
            get
            {
                return this.partConditionField;
            }
            set
            {
                this.partConditionField = value;
            }
        }

        /// <remarks/>
        public bool hasPartManufacturerApproval
        {
            get
            {
                return this.hasPartManufacturerApprovalField;
            }
            set
            {
                this.hasPartManufacturerApprovalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasPartManufacturerApprovalSpecified
        {
            get
            {
                return this.hasPartManufacturerApprovalFieldSpecified;
            }
            set
            {
                this.hasPartManufacturerApprovalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime manufacturingDate
        {
            get
            {
                return this.manufacturingDateField;
            }
            set
            {
                this.manufacturingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool manufacturingDateSpecified
        {
            get
            {
                return this.manufacturingDateFieldSpecified;
            }
            set
            {
                this.manufacturingDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public partInformationExpiryInformation expiryInformation
        {
            get
            {
                return this.expiryInformationField;
            }
            set
            {
                this.expiryInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class partInformationBatchNumberInformation
    {

        private string batchNumberField;

        private string supplierBatchNumberField;

        /// <remarks/>
        public string batchNumber
        {
            get
            {
                return this.batchNumberField;
            }
            set
            {
                this.batchNumberField = value;
            }
        }

        /// <remarks/>
        public string supplierBatchNumber
        {
            get
            {
                return this.supplierBatchNumberField;
            }
            set
            {
                this.supplierBatchNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class partInformationExpiryInformation
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expiryDate", typeof(System.DateTime), DataType = "date")]
        [System.Xml.Serialization.XmlElementAttribute("hasUnlimitedExpiryDate", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("useManufacturingDate", typeof(bool))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        expiryDate,

        /// <remarks/>
        hasUnlimitedExpiryDate,

        /// <remarks/>
        useManufacturingDate,
    }
}